<?php
$config['municipal'] = array(
    'title' => 'Муниципальный заказ',
    'access' => true,
    'includes' => array(
        'views' => array(
            'addAuction/form.php',    
            'addConcurs/form.php',    
            'addQuotation/form.php',
            'addEAuction/form.php',    
            'addPhysicalBody/form.php',    
            'addLegalBody/form.php',    
            'archiveOfAuction/index.php',    
            'archiveOfConcurs/index.php',    
            'archiveOfQuotations/index.php',    
            'budgetPeoples/index.php',    
            'budgetPeoples/form.php',    
            'declaredAuction/index.php',    
            'declaredConcurs/index.php',    
            'listQuotations/index.php',    
            'plannedEAuction/index.php',    
            'currentEAuction/index.php',    
            'archiveOfEAuction/index.php',    
            'legalBody/index.php',    
            'physicalBody/index.php',    
//            'magazineOfEvents',    
            'nomenclatureDirectory/sections.php',    
            'nomenclatureDirectory/form.php',    
            'registerOfContracts/index.php',    
            'registerOfContracts/search.php',    
//            'search',    
            'workingCalendar/index.php',    
            'municipal/addFile.php',    
            'municipal/files.php'    
        ),
        'models' => array(
            'municipal_model.php',
            'addAuction_model.php',    
            'addConcurs_model.php',    
            'addQuotation_model.php',    
            'addEAuction_model.php',    
            'addPhysicalBody_model.php',    
            'addLegalBody_model.php',    
            'archiveOfAuction_model.php',    
            'archiveOfConcurs_model.php',    
            'archiveOfQuotations_model.php',    
            'budgetPeoples_model.php',    
            'declaredAuction_model.php',    
            'declaredConcurs_model.php',    
            'listQuotations_model.php',    
            'plannedEAuction_model.php',    
            'currentEAuction_model.php',    
            'archiveOfEAuction_model.php',    
//            'magazineOfEvents_model.php',            
            'nomenclatureDirectory_model.php',    
            'registerOfContracts_model.php',    
//            'search_model.php',    
            'workingCalendar_model.php',
            'physicalBody_model.php',    
            'legalBody_model.php'  
        )
    ),
    'TABLES' => array(
        'Sections'      => 'th_municipal_sections',
        'Calendar'      => 'th_municipal_calendar',
        'Auctions'      => 'th_municipal_auctions',
        'Concurs'       => 'th_municipal_concurs',
        'Quotations'    => 'th_municipal_quotations',
        'EAuctions'     => 'th_municipal_eauctions',
        'PhysicalBody'  => 'th_municipal_physicalbody',
        'LegalBody'     => 'th_municipal_legalbody',
        'BudgetPeoples' => 'th_municipal_budgetpeoples',
        'Files'         => 'th_municipal_files'
    ),
    'upload' => array(
        'upload_path' => './uploads/municipal/',
        'allowed_types' => 'zip',
        'overwrite' => FALSE,
        'max_size' => 2048000,
        'max_width' => 0,
        'max_height' => 0,
        'encrypt_name' => TRUE,
        'remove_spaces' => TRUE
    ),
    
    // Месяцы
    'month' => array('01' => 'Январь','02' => 'Февраль','03' => 'Март','04' => 'Апрель','05' => 'Май','06' => 'Июнь','07' => 'Июль','08' => 'Август','09' => 'Сентябрь','10' => 'Октябрь','11' => 'Ноябрь','12' => 'Декабрь'),
    
    // Дни
    'day' => array('01' => 1,'02' => 2,'03' => 3,'04' => 4,'05' => 5,'06' => 6,'07' => 7,'08' => 8,'09' => 9,'10' => 10,'11' => 11,'12' => 12,'13' => 13,'14' => 14,'15' => 15,'16' => 16,'17' => 17,'18' => 18,'19' => 19,'20' => 20,'21' => 21,'22' => 22,'23' => 23,'24' => 24,'25' => 25,'26' => 26,'27' => 27,'28' => 28,'29' => 29,'30' => 30,'31' => 31),
    
    // Часы
    'hour' => array('00' => '00','01' => '01','02' => '02','03' => '03','04' => '04','05' => '05','06' => '06','07' => '07','08' => '08','09' => '09','10' => '10','11' => '11','12' => '12','13' => '13','14' => '14','15' => '15','16' => '16','17' => '17','18' => '18','19' => '19','20' => '20','21' => '21','22' => '22','23' => '23'),
    
    // Минуты
    'minute' => array('00' => '00','01' => '01','02' => '02','03' => '03','04' => '04','05' => '05','06' => '06','07' => '07','08' => '08','09' => '09','10' => '10','11' => '11','12' => '12','13' => '13','14' => '14','15' => '15','16' => '16','17' => '17','18' => '18','19' => '19','20' => '20','21' => '21','22' => '22','23' => '23','24' => '24','25' => '25','26' => '26','27' => '27','28' => '28','29' => '29','30' => '30','31' => '31','32' => '32','33' => '33','34' => '34','35' => '35','36' => '36','37' => '37','38' => '38','39' => '39','40' => '40','41' => '41','42' => '42','43' => '43','44' => '44','45' => '45','46' => '46','47' => '47','48' => '48','49' => '49','50' => '50','51' => '51','52' => '52','53' => '53','54' => '54','55' => '55','56' => '56','57' => '57','58' => '58','59' => '59'),
    
    'validation' => array(
        'Auction' => array(
            'rules' => array(
                'number'                                => 'trim|required|xss_clean',
                'title'                                 => 'trim|required|xss_clean',
                'section'                               => 'required',
                'fundingOrder'                          => 'trim|required|xss_clean',
                'dateHolding'                           => 'required',
                'customer'                              => 'trim|required|xss_clean',
                'authorisedBody'                        => 'trim|required|xss_clean',
                'placeOrderAndTimeOfAuction'            => 'trim|required|xss_clean',
                'subjectMunicipalContract'              => 'trim|required|xss_clean',
                'locationWorksAndServices'              => 'trim|required|xss_clean',
                'procedureForPaymentOfGoods'            => 'trim|required|xss_clean',
                'initialContractPrice'                  => 'trim|required|xss_clean',
                'advantageOIAndUIS'                     => 'trim|required|xss_clean',
                'termPlaceAndOrderAndOfficialSite'      => 'trim|required|xss_clean',
                'contractEnforcement'                   => 'trim|required|xss_clean',
                'ensuringApplication'                   => 'trim|required|xss_clean',
                'placeOrderDates'                       => 'trim|required|xss_clean'
            ),
            'fields' => array(
                'number'                                => 'Номер аукциона',
                'title'                                 => 'Название',
                'section'                               => 'Раздел номенклатурного справочника',
                'fundingOrder'                          => 'Источник финансирования заказа',
                'dateHolding'                           => 'Дата проведения',
                'customer'                              => 'Заказчик',
                'authorisedBody'                        => 'Уполномоченный орган',
                'placeOrderAndTimeOfAuction'            => 'Место, порядок и время проведения аукциона',
                'subjectMunicipalContract'              => 'Предмет муниципального контракта',
                'locationWorksAndServices'              => 'Место, условия и сроки поставок товара, выполнения работ, оказания услуг',
                'procedureForPaymentOfGoods'            => 'Форма, сроки и порядок оплаты товара (работ, услуг)',
                'initialContractPrice'                  => 'Начальная (максимальная) цена контракта',
                'advantageOIAndUIS'                     => 'Преимущества ОИ и УИС',
                'termPlaceAndOrderAndOfficialSite'      => 'Срок, место и порядок предоставления документации об аукционе , официальный сайт на котором размещена документация об аукционе',
                'contractEnforcement'                   => 'Обеспечение исполнения контракта',
                'ensuringApplication'                   => 'Обеспечение заявки',
                'placeOrderDates'                       => 'Место, порядок, даты начала и окончания подачи заявок на участие в аукционе'
            )
        ),
        'Concurs' => array(
            'rules' => array(
                'number'                                => 'trim|required|xss_clean',
                'title'                                 => 'trim|required|xss_clean',
                'section'                               => 'required',
                'dataToOpen'                            => 'required',
                'startPrice'                            => 'trim|required|xss_clean',
                'customer'                              => 'trim|required|xss_clean',
                'authorisedBody'                        => 'trim|required|xss_clean',
                'demandMaintenance'                     => 'trim|required|xss_clean',
                'maintenanceOfExecutionOfTheContract'   => 'trim|required|xss_clean',
                'competitionSubject'                    => 'trim|required|xss_clean',
                'advantageOIAndUIS'                     => 'trim|required|xss_clean',
                'placeOfDeliveryOfTheGoods'             => 'trim|required|xss_clean',
                'termsOfDeliveriesOfTheGoods'           => 'trim|required|xss_clean',
                'termPlaceAndOrderAndOfficialSite'      => 'trim|required|xss_clean',
                'placeOrderDates'                       => 'trim|required|xss_clean',
                'placeDateAndOpeningTime'               => 'trim|required|xss_clean'
            ),    
            'fields' => array(
                'number'                                => 'Номер конкурса',
                'title'                                 => 'Название',
                'section'                               => 'Раздел номенклатурного справочника',
                'dataToOpen'                            => 'Дата вскрытия конвертов с заявками',
                'startPrice'                            => 'Начальная (максимальная) цена контракта',
                'customer'                              => 'Заказчик',
                'authorisedBody'                        => 'Уполномоченный орган',
                'demandMaintenance'                     => 'Обеспечение заявки',
                'maintenanceOfExecutionOfTheContract'   => 'Обеспечение исполнения контракта',
                'competitionSubject'                    => 'Предмет конкурса',
                'advantageOIAndUIS'                     => 'Преимущества ОИ и УИС',
                'placeOfDeliveryOfTheGoods'             => 'Место поставки товара (выполнения работ, оказания услуг)',
                'termsOfDeliveriesOfTheGoods'           => 'Сроки (периоды) поставок товара (выполнения работ, оказания услуг)',
                'termPlaceAndOrderAndOfficialSite'      => 'Срок, место и порядок предоставления конкурсной документации, официальный сайт, на котором размещена конкурсная документация',
                'placeOrderDates'                       => 'Место, порядок, даты начала и окончания подачи заявок на участие в конкурсе',
                'placeDateAndOpeningTime'               => 'Место, дата и время вскрытия конвертов с заявками на участие в конкурсе'    
            )    
        ),
        'Quotation' => array(
            'rules' => array(
                'section'                               => 'required',   
                'customer'                              => 'trim|required|xss_clean',   
                'number'                                => 'trim|required|xss_clean',
                'fundingOrder'                          => 'trim|required|xss_clean',
                'nameCharacteristicsQuantityWorks'      => 'trim|required|xss_clean',
                'placeDeliveryWorks'                    => 'trim|required|xss_clean',
                'timingDeliveriesWorksServices'         => 'trim|required|xss_clean',
                'detailsIncludedPriceWorksServices'     => 'trim|required|xss_clean',
                'maximumPriceContract'                  => 'trim|required|xss_clean',
                'placeSubmissionQuotedApplications'     => 'trim|required|xss_clean',
                'dateSubmissionQuotedApplications'      => 'required',
                'termsOfDeliveriesOfTheGoods'           => 'trim|required|xss_clean',
                'receptionDateClosed'                   => 'required'
            ),
            'fields' => array(
                'section'                               => 'Раздел номенклатурного справочника',   
                'customer'                              => 'Заказчик',   
                'number'                                => 'Номер',
                'fundingOrder'                          => 'Источник финансирования заказа',
                'nameCharacteristicsQuantityWorks'      => 'Наименование, характеристики и количество поставляемых товаров, наименование и объем выполняемых работ',
                'placeDeliveryWorks'                    => 'Место доставки поставляемых товаров, место выполнения работ, место оказания услуг',
                'timingDeliveriesWorksServices'         => 'Сроки поставок товаров, выполнения работ, оказания услуг',
                'detailsIncludedPriceWorksServices'     => 'Сведения о включенных (не включенных) в цену товаров, работ, услуг расходах, в том числе расходах на перевозку, страхование, уплату таможенных пошлин, налогов, сборов и других обязательных платежей',
                'maximumPriceContract'                  => 'Максимальная цена контракта, определяемая заказчиком, в результате изучения рынка необходимых товаров, работ, услуг',
                'placeSubmissionQuotedApplications'     => 'Место подачи котировочных заявок',
                'dateSubmissionQuotedApplications'      => 'Дата подачи котировочной заявки, дата публикации на сайте',
                'termsOfDeliveriesOfTheGoods'           => 'Срок и условия оплаты поставок товаров, выполнения работ, оказания услуг',
                'receptionDateClosed'                   => 'Дата окончания приема'
            )   
        ),
        
        'EAuction' => array(
            'rules' => array(
                'number'                        => 'trim|required|xss_clean',
                'section'                       => 'required',
                'title'                         => 'trim|required|xss_clean',
                'dateStartWork'                 => 'required',
                'timeStartOrEnd'                => 'required',
                'customer'                      => 'trim|required|xss_clean',
                'authorisedBody'                => 'trim|required|xss_clean',
                'fundingOrder'                  => 'trim|required|xss_clean',
                'subjectMunicipalContract'      => 'trim|required|xss_clean',
                'locationWorksAndServices'      => 'trim|required|xss_clean',
                'procedureForPaymentOfGoods'    => 'trim|required|xss_clean',
                'initialContractPrice'          => 'trim|required|xss_clean',
                'advantageOIAndUIS'             => 'trim|required|xss_clean',
                'termPlaceOrderDocumentation'   => 'trim|required|xss_clean'
            ),
            'fields' => array(
                'number'                        => 'Номер',
                'section'                       => 'Раздел номенклатурного справочника',
                'title'                         => 'Наименование',
                'dateStartWork'                 => 'Дата начала работы',
                'timeStartOrEnd'                => 'Время старта и окончания в течении суток',
                'customer'                      => 'Заказчик',
                'authorisedBody'                => 'Уполномоченный орган',
                'fundingOrder'                  => 'Источник финансирования заказа',
                'subjectMunicipalContract'      => 'Предмет муниципального контракта',
                'locationWorksAndServices'      => 'Место, условия и сроки поставок товара, выполнения работ, оказания услуг',
                'procedureForPaymentOfGoods'    => 'Форма, сроки и порядок оплаты товара, работ или услуг',
                'initialContractPrice'          => 'Начальная (максимальная) цена контракта',
                'advantageOIAndUIS'             => 'Преимущества ОИ и УИС',
                'termPlaceOrderDocumentation'   => 'Срок, место и порядок предоставления документации'
            )
        ),
        'LegalBody' => array(
            'rules' => array(
                'fullName'                          => 'trim|required|xss_clean',
                'shortName'                         => 'trim|required|xss_clean',
                'formEntity'                        => 'trim|required|xss_clean',
                'inn'                               => 'trim|required|xss_clean',
                'kpp'                               => 'trim|required|xss_clean',
                'producer'                          => 'trim|xss_clean',
                'stateRegistrationCertificate'      => 'trim|required|xss_clean',
                'number'                            => 'trim|required|xss_clean',
                'dateIssue'                         => 'trim|required|xss_clean',
                'issued'                            => 'trim|required|xss_clean',
                'region'                            => 'trim|required|xss_clean',
                'city'                              => 'trim|required|xss_clean',
                'legalAddress'                      => 'trim|required|xss_clean',
                'mailingAddress'                    => 'trim|required|xss_clean',
                'phone'                             => 'trim|required|xss_clean',
                'fax'                               => 'trim|required|xss_clean',
                'email'                             => 'trim|required|xss_clean',
                'nameHead'                          => 'trim|required|xss_clean',
                'postHead'                          => 'trim|required|xss_clean',
                'nameAndPassportDetailsFounders'    => 'trim|required|xss_clean',
                'typesActivitiesCharter'            => 'trim|required|xss_clean',
                'shortInfoResourses'                => 'trim|required|xss_clean',
                'siteUrl'                           => 'trim|required|xss_clean'
            ),
            'fields' => array(
                'fullName'                          => 'Полное наименование организации',
                'shortName'                         => 'Краткое наименование организации',
                'formEntity'                        => 'Организационно-правовая форма',
                'inn'                               => 'ИНН',
                'kpp'                               => 'КПП',
                'producer'                          => 'Производитель (да/нет)',
                'stateRegistrationCertificate'      => 'Свидетельство о государственной регистрации',
                'number'                            => 'Номер',
                'dateIssue'                         => 'Дата выдачи',
                'issued'                            => 'Кем выдан',
                'region'                            => 'Регион',
                'city'                              => 'Город',
                'legalAddress'                      => 'Юридический адрес',
                'mailingAddress'                    => 'Почтовый адрес',
                'phone'                             => 'Телефон',
                'fax'                               => 'Факс',
                'email'                             => 'E-mail',
                'nameHead'                          => 'Ф.И.О. руководителя',
                'postHead'                          => 'Должность руководителя',
                'nameAndPassportDetailsFounders'    => 'Ф.И.О. и паспортные данные учредителей',
                'typesActivitiesCharter'            => 'Виды деятельности в соответствии с Уставом',
                'shortInfoResourses'                => 'Краткая информация о материально-технических, трудовых ресурсах предприятия',
                'siteUrl'                           => 'Адрес сайта в Интернет'
            )     
        ),
        'PhysicalBody' => array(
            'rules' => array(
                'surname'       => 'trim|required|xss_clean',
                'name'          => 'trim|required|xss_clean',
                'patronymic'    => 'trim|required|xss_clean',
                'dateOfBirth'   => 'trim|required|xss_clean',
                'inn'           => 'trim|required|xss_clean',
                'documentName'  => 'trim|required|xss_clean',
                'series'        => 'trim|required|xss_clean',
                'number'        => 'trim|required|xss_clean',
                'dateIssue'     => 'trim|required|xss_clean',
                'issued'        => 'trim|required|xss_clean',
                'region'        => 'trim|required|xss_clean',
                'city'          => 'trim|required|xss_clean',
                'address'       => 'trim|required|xss_clean',
                'phone'         => 'trim|required|xss_clean',
                'fax'           => 'trim|required|xss_clean',
                'email'         => 'trim|required|xss_clean',
                'activities'    => 'trim|required|xss_clean',
                'siteUrl'       => 'trim|required|xss_clean'
            ),
            'fields' => array(
                'surname'       => 'Фамилия',
                'name'          => 'Имя',
                'patronymic'    => 'Отчество',
                'dateOfBirth'   => 'Дата рождения',
                'inn'           => 'ИНН',
                'documentName'  => 'Наименование документа',
                'series'        => 'Серия',
                'number'        => 'Номер',
                'dateIssue'     => 'Дата выдачи',
                'issued'        => 'Кем выдан',
                'region'        => 'Регион',
                'city'          => 'Город',
                'address'       => 'Адрес',
                'phone'         => 'Телефон',
                'fax'           => 'Факс',
                'email'         => 'E-mail',
                'activities'    => 'Виды деятельности',
                'siteUrl'       => 'Адрес сайта в Интернет'
            )
        ),
        
        'BudgetPeoples' => array(
            'rules' => array(
                'title'                 => 'trim|required|xss_clean',
                'shortTitle'            => 'trim|required|xss_clean',
                'inn'                   => 'trim|required|xss_clean',
                'kpp'                   => 'trim|required|xss_clean',
                'bik'                   => 'trim|required|xss_clean',
                'settlementAccount'     => 'trim|required|xss_clean',
                'correspondentAccount'  => 'trim|required|xss_clean',
                'bank'                  => 'trim|required|xss_clean',
                'okonk'                 => 'trim|required|xss_clean',
                'okpo'                  => 'trim|required|xss_clean',
                'phone'                 => 'trim|required|xss_clean',
                'fax'                   => 'trim|required|xss_clean',
                'nameHead'              => 'trim|required|xss_clean',
                'email'                 => 'trim|required|xss_clean',
                'legalAddress'          => 'trim|required|xss_clean',
                'mailingAddress'        => 'trim|required|xss_clean'
            ),
            'fields' => array(
                'title'                 => 'Название',
                'shortTitle'            => 'Краткое название',
                'inn'                   => 'ИНН',
                'kpp'                   => 'КПП',
                'bik'                   => 'БИК',
                'settlementAccount'     => 'Расчетный счет',
                'correspondentAccount'  => 'Кор. счет',
                'bank'                  => 'Банк',
                'okonk'                 => 'ОКОНК',
                'okpo'                  => 'ОКПО',
                'phone'                 => 'Телефон',
                'fax'                   => 'Факс',
                'nameHead'              => 'Ф.И.О. руководителя',
                'email'                 => 'E-mail',
                'legalAddress'          => 'Юридический адрес',
                'mailingAddress'        => 'Почтовый адрес' 
            )
        ),
        'RegisterOfContracts' => array(
            'rules' => array(
                'from'      => 'required',
                'to'        => 'required',
                'object'    => 'trim|required|numeric|xss_clean'
            ),
            'fields' => array(
                'from'      => 'С',
                'to'        => 'По',
                'object'    => 'Где искать'
            )
        )
    )
);
?>
